/*
	MetadataParser.mm
	Spim Interface

	Created by Jonny Taylor on 22/12/2017.
	
	Parses metadata of image files generated by Spim GUI.
	This code primarily belongs in that project, but it is also useful
	for other projects that work with data in that format	*/

#import "MetadataParser.h"
#import "jCocoaImageUtils.h"
#import "DictionaryReadingExtensions.h"
#import "jCache.h"

NSArray *DumpDiffsFromFrameInFolder(NSString *path)
{
    // This is example code reminding me how to extract and dump out the 'diffs' property from a brightfield frame.
    // This example is intended to see the diffs associated with the final frame of a set of ref frames.
    
    // Open the first [and probably only] file in folder, in order to create the FrameMetadataParser object
    MetadataForFrame *metadata = [MetadataForFrame metadataForFirstFrameInFolder:path];
    // ... but switch to the final frame in that file
    metadata = [metadata.parser metadataForFrame:metadata.parser.frameCount-1];
    
    // Decompress the diffs property
    id arr = [metadata valueForKeyPath:@"frame.sync_info.diffs"];
    ALWAYS_ASSERT(arr != nil);
    NSArray *diffs = [NSPropertyListSerialization propertyListWithData:arr options:0 format:nil error:nil];
    
    // Print out its contents
    printf("# %s\n", path.UTF8String);
    printf("# Length %zd\n", diffs.count);
    for (size_t i = 0; i < diffs.count; i++)
        printf("%zd\t%lf\n", i, ((NSNumber *)diffs[i]).doubleValue);
    
    return diffs;
}

@implementation ParserBase

-(id)init
{
	if (!(self = [super init]))
		return nil;
	return self;
}

-(id)valueForKeyPath:(NSString *)keyPath
{
	// This method is implemented by subclasses - should never get here.
	ALWAYS_ASSERT(0);
}

#define DICTIONARY_CLASS ParserBase
#include "DictionaryReadingExtensionsImplementation.mm"

@end

@interface JDictionary()
	@property (readwrite, retain) NSDictionary *dict;
@end

@implementation JDictionary
/*	This is just a wrapper for NSDictionary
	I used to have the typed accessors as a category on NSDictionary, but it's convenient to have them
	in a separate class so I can also implement FrameMetadataParser on top of it
	(which does not implement everything in NSDictionary)	*/

+(id)jDictionary:(NSDictionary *)inDict
{
	return [[[JDictionary alloc] initWithDictionary:inDict] autorelease];
}

-(id)initWithDictionary:(NSDictionary *)inDict
{
	if (!(self = [super init]))
		return nil;
	self.dict = inDict;
	return self;
}

-(void)dealloc
{
	self.dict = nil;
	[super dealloc];
}

-(id)valueForKeyPath:(NSString *)keyPath
{
	return [_dict valueForKeyPath:keyPath];
}

@synthesize dict = _dict;

@end

@interface MetadataForFrame()
	@property (readwrite, retain) FrameMetadataParser *parser;
	@property (readwrite) size_t arrayIndex;
@end

@implementation MetadataForFrame

-(id)initForParser:(FrameMetadataParser *)inParser arrayIndex:(size_t)inArrayIndex
{
	if (!(self = [super init]))
		return nil;
	
	self.parser = inParser;
	self.arrayIndex = inArrayIndex;
	
	return self;
}

+(MetadataForFrame *)metadataForFirstFrameInFolder:(NSString *)path
{
    return [MetadataForFrame metadataForFirstFrameAtImagePath:FirstImageFileNameInDirectory(path)];
}

+(MetadataForFrame *)metadataForFirstFrameAtImagePath:(NSString *)path
{
	FrameMetadataParser *parser = [FrameMetadataParser parserForImagePath:path];
	return [parser metadataForFrame:0];
}

-(void)dealloc
{
	self.parser = nil;
	[super dealloc];
}

-(id)valueForKeyPath:(NSString *)keyPath
{
	return [self.parser valueForKeyPath:keyPath arrayIndex:self.arrayIndex];
}

-(int)frameNumber
{
	return [self getOptionalIntForKey:@"frame.frame_number" defaultVal:0];
}

-(double)universalComputerTimestamp
{
	/*  We go through a bit of a faff to determine a timestamp, since I have done various things in previous versions of code.
	 I used to just record time_received. Then I realised that for QI cameras I could record the time exposure finished.
	 I initially called that time_received3, then changed it to a more helpful name.   */
	NSNumber *timestamp = [self valueForKeyPath:@"frame.time_exposed"];
	if (timestamp == nil)
	{
		timestamp = [self valueForKeyPath:@"frame.time_received3"];	// I used this for a brief while before renaming it to time_exposed
		if (timestamp == nil)
			timestamp = [self valueForKeyPath:@"frame.time_received"];
	}
	
	if (timestamp != nil)
	{
		// We use timebase_start_uptime to correct the value and get a universally consistent timestamp
		// I leave it optional just to cope with synthetic plists where I probably didn't bother to define timebase_start_uptime
		return timestamp.doubleValue + [self getOptionalDoubleForKey:@"camera.timebase_start_uptime" defaultVal:0];
	}
	else
		return 0.0;
}

-(NSPoint)driftOffset
{
	NSString *offset = [self getOptionalStringForKey:@"frame.drift_offset" defaultVal:nil];
	NSPoint result;
	if (offset == nil)
	{
		// Back-compatibility with old plist format
		result = NSMakePoint(((NSNumber*)[self valueForKeyPath:@"sync_settings.drift_offset_x"]).floatValue,
							 ((NSNumber*)[self valueForKeyPath:@"sync_settings.drift_offset_y"]).floatValue);
	}
	else
		result = NSPointFromString(offset);
	return result;
}

-(NSBitmapImageRep *)frameBitmap
{
	return [self.parser frameBitmapForArrayIndex:self.arrayIndex];
}

-(NSString *)imageFileFullPath { return self.parser.imagePath; }
-(NSString *)frameDescNoPath
{
	if (self.parser.frameCount > 1)
		return [SWF:@"%@ [%zd]", self.parser.imageFilename, self.arrayIndex];
	else
		return self.parser.imageFilename;
}

-(bool)metadataAvailable { return self.parser.metadataAvailable; }

-(NSMutableDictionary *)frameSpecificMetadataDictionary
{
	return [self.parser frameSpecificMetadataDictionaryForArrayIndex:self.arrayIndex];
}

-(NSDictionary *)commonMetadataDictionary
{
	return self.parser.commonMetadataDictionary;
}

-(void)setNewObject:(id)obj forFrameKey:(NSString *)key
{
	[self.parser setNewObject:obj forFrameKey:key arrayIndex:self.arrayIndex];
}

-(void)setNewObject:(id)obj forCommonKey:(NSString *)key
{
	[self.parser setNewObject:obj forCommonKey:key arrayIndex:self.arrayIndex];
}

-(void)saveStandaloneMetadataFileAtPath:(NSString *)destPath
{
    if (self.frameSpecificMetadataDictionary != nil)        // Catch case where we have no metadata associated with the image
    {
        NSMutableDictionary *metadataToWrite = [NSMutableDictionary dictionaryWithDictionary:self.commonMetadataDictionary];
        [metadataToWrite setObject:[NSArray arrayWithObject:self.frameSpecificMetadataDictionary] forKey:@"frames"];
        bool ok = [metadataToWrite writeToFile:destPath atomically:NO];
        CHECK(ok);
    }
}

@synthesize parser = _parser;
@synthesize arrayIndex = _arrayIndex;

@end

@interface FrameMetadataParser()
	@property (readwrite, retain) NSArray *frameMetadataArray;
	@property (readwrite, retain) JAlias *folderAlias;
	@property (readwrite, retain) NSString *imageFilename;
	@property (readwrite) size_t frameCount;
@end

@implementation FrameMetadataParser

/*	I am attempting a caching strategy to improve performance when reading multi-page TIFFs.
	NSCache ought to be able to keep any current multi-page images around for when we access
	the next page, but then automatically clear things out once we move on to another file.
	This should help a lot with e.g. MovieBuilder, where we have a small set of sequences for
	which we will read repeatedly from the same small set of files before moving on to another set.
	The worry is that the documentation for NSCache is extremely vague in terms of making any
	promises about how strictly the cost limit is enforced, and even what order things will be
	evicted from the cache! As a result I don't have total confidence that this will protect me
	from using up all memory. However, I think I will try it and see if we encounter problems.	*/
const NSUInteger kMaxCacheSizeInBytes = (NSUInteger)1e9;
JCache *imageCache = [JCache new];

+(id)parserForImagePath:(NSString *)imagePath
{
	
	return [FrameMetadataParser parserForImageFilename:imagePath.lastPathComponent
											  inFolder:[JAlias aliasForPath:imagePath.stringByDeletingLastPathComponent]];
}

+(id)parserForImageFilename:(NSString *)inImageFilename inFolder:(JAlias *)inFolderAlias
{
	// This version is more efficient when iterating over a whole directory -
	// it is actually quite costly to create an alias.
	// This is still not ideal - it's even costly to resolve one!
	// However, that's only a 20% hit for single-page TIFFs, and should be less of an overhead for multi-page tiffs
	// since we do more work with each plist file.
	// I am therefore going to leave things like this.
	imageCache.totalCostLimit = kMaxCacheSizeInBytes;
	NSDictionary *theDictionary = [NSDictionary dictionaryWithContentsOfFile:MetadataPathFromImagePath([inFolderAlias.path stringByAppendingPathComponent:inImageFilename])];
	/*	Even if the metadata is not found, we can still create an object.
		It won't be very informative, of course, but it allows interfaces such as MovieBuilder
		to work fairly much the same whether or not metadata is present	*/
	return [[[FrameMetadataParser alloc] initWithDictionary:theDictionary forImageFilename:inImageFilename inFolder:inFolderAlias] autorelease];
}

-(id)initWithDictionary:(NSDictionary *)inDict forImageFilename:(NSString *)inImageFilename inFolder:(JAlias *)inFolderAlias
{
	if (!(self = [super initWithDictionary:inDict]))
		return nil;
	
	/*	Note: with an SSD drive, and old-style single-frame plists,
		creating this alias actually takes a significant fraction of the total execution time.
		It would therefore be desirable to do this a different way.
		In principle I could do it by only having one bookmark for the whole folder,
		and resolving everything relative to that.
		I could consider that (and/or perhaps creating a bookmark relative to an existing bookmark 
		might be possible and faster?)		*/
	if (inFolderAlias != nil)
	{
		self.folderAlias = inFolderAlias;
		ALWAYS_ASSERT(inImageFilename != nil);
		self.imageFilename = inImageFilename;
	}
	
	if (inDict != nil)
	{
		//	Get a direct pointer to the frame array object in the metadata.
		self.frameMetadataArray = [inDict objectForKey:@"frames"];
		if (self.frameMetadataArray == nil)
		{
			/*	In the case of old metadata versions, this will not exist, in which case we expect the equivalent metadata keys
				to be present at the root level in the plist file.	To keep our implementation here tidy, we synthesize an array
				with only one entry, which is the whole metadata dictionary.
				That way we can always access the frame data (arrayIndex=0 in this case) through self.frameMetadataArray,
				even for old metadata versions that are not structured that way.	*/
			self.frameMetadataArray = [NSArray arrayWithObject:inDict];
		}
		self.frameCount = self.frameMetadataArray.count;
	}
	else
	{
		/*	No metadata available (just an image file).
			Unfortunately there's nothing we can do except access the image file in order to determine
			how many images might be in it.
			That's going to be really inefficient, but hopefully it won't happen too often,
			since it won't happen with data we have previously recorded ourselves...	*/
		self.frameCount = self.multiPageImage.representations.count;
	}
	
	// Identify the metadata version
	if (inDict == nil)
		metadataVersion = 0;
	else
		metadataVersion = [super getOptionalIntForKey:@"metadata_version" defaultVal:kSingleFileMetadataVersion];
	
	return self;
}

-(void)dealloc
{
	/*	This might be a bit too dramatic a move, but I clear the associated path from the cache when
		this parser is released (which will happen when all frame parsers that reference it are also deleted).
		That should ensure the cache can do its job, but also prevents it being left full with stale data,
		since I am worried about memory running low on 32-bit systems	*/
	[imageCache removeObjectForKey:self.imagePath];
	
	self.frameMetadataArray = nil;
	self.folderAlias = nil;
	self.imageFilename = nil;
	[super dealloc];
}

-(NSString *)imagePath { return [self.folderAlias.path stringByAppendingPathComponent:self.imageFilename]; }

-(MetadataForFrame *)metadataForFrame:(size_t)arrayIndex
{
    // Note: we return an object even if there is no plist available -
    // the MetadataForFrame object also allows access to the frame image itself, so the caller may still want it.
    return [[[MetadataForFrame alloc] initForParser:self arrayIndex:arrayIndex] autorelease];
}

-(NSString *)translateKeyPath:(NSString *)keyPath
{
	if ((metadataVersion == kSingleFileMetadataVersion) ||
		(metadataVersion == kArrayAggregatedMetadataVersion))
	{
		NSArray *components = [keyPath componentsSeparatedByString:@"."];
		NSMutableArray *newComponents = [NSMutableArray arrayWithArray:components];
		NSString *firstComponent = components.firstObject;
		// Strip out any groupings that I didn't use in the early file format
		if ([firstComponent isEqualToString:@"camera"] ||
			[firstComponent isEqualToString:@"frame"] ||
			[firstComponent isEqualToString:@"video"])
		{
			[newComponents removeObjectAtIndex:0];
		}
		else if ([firstComponent isEqualToString:@"program"])
		{
			[newComponents replaceObjectAtIndex:0 withObject:@"program_info"];
		}
		// Catch camera.camera_properties, now that camera grouping has been removed
		if ([newComponents.firstObject isEqualToString:@"camera_properties"])
			[newComponents removeObjectAtIndex:0];
	
        if (metadataVersion == kArrayAggregatedMetadataVersion)
        {
            // Everything is presented as being in the frame-specific metadata
            return [@"frame." stringByAppendingString:[newComponents componentsJoinedByString:@"."]];
        }
        else
            return [newComponents componentsJoinedByString:@"."];
	}
	else
		return keyPath;
}

-(id)valueForKeyPath:(NSString *)keyPath arrayIndex:(size_t)arrayIndex
{
	// First catch the case where there is no underlying metadata (presumably just an image)
	if (self.dict == nil)
		return nil;

	// Now do any translation for back-compatibility with old file formats
	keyPath = [self translateKeyPath:keyPath];
	
	if ([keyPath hasPrefix:@"frame."])
	{
		// This is a frame-specific key, and we need to look in the appropriate entry in the frame array
		ALWAYS_ASSERT(arrayIndex < self.frameMetadataArray.count);
		NSDictionary *dictionaryToUse = [self.frameMetadataArray objectAtIndex:arrayIndex];
		ALWAYS_ASSERT([dictionaryToUse isKindOfClass:[NSDictionary class]]);
		return [dictionaryToUse valueForKeyPath:[keyPath substringFromIndex:6]];		// Skip the 'frame.' prefix
	}
	else
	{
		// Look directly in the dictionary for global metadata
		return [self.dict valueForKeyPath:keyPath];
	}
}

-(NSMutableDictionary *)frameSpecificMetadataDictionaryForArrayIndex:(size_t)arrayIndex
{
	/*	Use sparingly: returns the frame-specific metadata dictionary for a single frame.
		This may be useful if caller is writing out (edited) files to disk.
		Caller will need to make own decisions about whether to write files out as multi-page TIFFs or not	*/
	if (metadataVersion == kSingleFileMetadataVersion)
	{
		// No frames array, we just return everything as frame-specific metadata
		return [NSMutableDictionary dictionaryWithDictionary:self.dict];
	}
	else
	{
		NSArray *frameArray = [self.dict objectForKey:@"frames"];
		return [frameArray objectAtIndex:arrayIndex];
	}
}

-(NSDictionary *)commonMetadataDictionary
{
	if (metadataVersion == kSingleFileMetadataVersion)
	{
		// Although this is perhaps confusing, I want to return a common metadata dictionary that specifies
		// a metadata version of kArrayAggregatedMetadataVersion. This is because MovieBuilder is going to
		// aggregate multiple individual-frame dictionaries into a single plist file in that format,
		// and I want that plist file to be tagged with the correct version.
		return [NSDictionary dictionaryWithObject:[NSNumber numberWithInt:kArrayAggregatedMetadataVersion] forKey:@"metadata_version"];
	}
	else
	{
		NSMutableDictionary *result = [NSMutableDictionary dictionaryWithDictionary:self.dict];
		// Edit down the frame array to remove the frames object
		[result removeObjectForKey:@"frames"];
		return result;
	}
}

-(void)setNewObject:(id)obj forFrameKey:(NSString *)key arrayIndex:(size_t)arrayIndex
{
	/*	Edit the metadata.
		Note that this is very inefficient, at least in its current implementation.
		We end up copying around the entire metadata dictionary just to add one object
		(because the sub-objects are not mutable, when loaded from the plist)
		However, this is currently quite a rare thing to want to do
		(phase-stamping is the only reason, at the time of writing), so I am not too
		concerned about the performance, which should be adequate.	*/
	
	NSMutableDictionary *result = [NSMutableDictionary dictionaryWithDictionary:self.dict];
	if (metadataVersion == kSingleFileMetadataVersion)
	{
        if (obj == nil)
            [result removeObjectForKey:key];
        else
            [result setObject:obj forKey:key];
	}
	else
	{
		// Edit down the frame array to only contain the one relevant object
		NSMutableArray *frameArray = [NSMutableArray arrayWithArray:[result objectForKey:@"frames"]];
		NSMutableDictionary *frameDictionary = [NSMutableDictionary dictionaryWithDictionary:[frameArray objectAtIndex:arrayIndex]];
        if (obj == nil)
            [frameDictionary removeObjectForKey:key];
        else
            [frameDictionary setObject:obj forKey:key];
		[frameArray replaceObjectAtIndex:arrayIndex withObject:frameDictionary];
		[result setObject:frameArray forKey:@"frames"];
		self.frameMetadataArray = frameArray;
	}
	self.dict = result;
	metadataWasEdited = true;
}

-(void)setNewObject:(id)obj forCommonKey:(NSString *)keyPath arrayIndex:(size_t)arrayIndex;
{
	/*	TODO: I do not have a generic implementation for deep paths, yet.
		[I think it could be done fairly easily using a recursive helper function, I just haven't done it yet]
		Instead, for now, I just have a special-case implementation
		for the one use-case that I currently have (camera.camera_properties.pixels_per_um)
	 
		TODO: most of the time we shouldn't care what the array index is,
		and I find it rather unsatisfactory to be passing it in. In principle we may not even 
		be processing any particular frame at the point when we make this call.
		However, we need to know it if the plist format is kArrayAggregatedMetadataVersion.	*/
    NSArray *components = [keyPath componentsSeparatedByString:@"."];
    NSString *firstComponent = components.firstObject, *lastComponent = components.lastObject;
    NSMutableDictionary *result = [NSMutableDictionary dictionaryWithDictionary:self.dict];
    if (metadataVersion == kSingleFileMetadataVersion)
    {
        [result setObject:obj forKey:lastComponent];
    }
    else if (metadataVersion == kArrayAggregatedMetadataVersion)
    {
        [self setNewObject:obj forFrameKey:lastComponent arrayIndex:arrayIndex];
    }
    else
    {
        // Current file version
        NSMutableDictionary *cam = [NSMutableDictionary dictionaryWithDictionary:[result getRequiredDictionaryForKey:firstComponent]];
        if (components.count == 2)
        {
            [cam setObject:obj forKey:lastComponent];
        }
        else
        {
            NSString *secondComponent = [components objectAtIndex:1];
            ALWAYS_ASSERT(components.count == 3);   // Only this implemented so far
            NSMutableDictionary *prop = [NSMutableDictionary dictionaryWithDictionary:[cam getRequiredDictionaryForKey:secondComponent]];
            [prop setObject:obj forKey:lastComponent];
            [cam setObject:prop forKey:secondComponent];
        }
        [result setObject:cam forKey:firstComponent];
    }
	self.dict = result;
	metadataWasEdited = true;
}

-(bool)metadataAvailable { return (self.dict != nil); }

-(void)saveMetadataIfNeeded
{
	/*	Save the metadata if it has been edited.
		In the case of multi-page tiffs, it would be terribly inefficient if we saved the entire plist file
		after every frame was processed. Instead we rely on the caller to set deferMetadataSaving if they know
		there will be more frames to come.
		That will break if the user stops playback early, but they'll just have to put up with that!
	 */
	if (metadataWasEdited && (!self.deferMetadataSaving))
		[self.dict writeToFile:MetadataPathFromImagePath(self.imagePath) atomically:NO];
}

-(NSImage *)multiPageImage
{
	// Load the image if necessary, but attempt to cache it since it will probably be used again pretty soon.
    // Note that resolving self.imagePath is actually costly in itself!
    // I at least cache that once at the start of this function now.
    NSString *imagePath = self.imagePath;
	NSImage *result = [imageCache objectForKey:imagePath];
	if (result != nil)
	{
		// Success - file is in cache
		return result;
	}
	
	/*	Image for this file is not in cache - load it.
		The standard NSImage loading code seems to require 3x as much virtual memory as the actual image on disk!
		(It appears to mmap the file, separately load the data into memory, and then provide separate memory for each bitmap(!?))
		The upshot is that this has a big memory footprint on 32-bit systems.
		Because of this I just load the damn thing myself using libtiff!	*/
	NSImage *theImage;
	if ([imagePath hasSuffix:@".tif"] ||
		[imagePath hasSuffix:@".tiff"])
	{
		theImage = NSImageFromTiffFile(imagePath);
	}
	else
		theImage = [[[NSImage alloc] initWithContentsOfFile:imagePath] autorelease];
	if (theImage == nil)
	{
		/*	In the past (some time before Jan 2018) I've encountered problems where we occasionally fail to load
			an image, and I have a suspicion that may be due to something related to spotlight indexing.
			I wanted to see if an immediate second try helps or not.
			(I suspect we are much less likely to encounter that problem anyway, nowadays, since I am encouraging
			people to disable spotlight indexing in folders where they are saving video files, for performance reasons)	*/
		NSLog(@"File not found at %@. Trying again\n", imagePath);
		theImage = [[[NSImage alloc] initWithContentsOfFile:imagePath] autorelease];
		if (theImage == nil)
			NSLog(@"Retry failed\n");
		else
			NSLog(@"Retry succeeded\n");
	}
	if (theImage == nil)
		return nil;
	
	// Add image to cache, once we have worked out how big it is
	NSInteger size = 0;
	for (NSBitmapImageRep *rep in theImage.representations)
	{
		if ([rep isKindOfClass:[NSBitmapImageRep class]])
			size += rep.bytesPerPlane * rep.numberOfPlanes;
	}
	[imageCache setObject:theImage forKey:imagePath cost:size];
	
	return theImage;
}

-(NSBitmapImageRep *)frameBitmapForArrayIndex:(size_t)arrayIndex
{
	NSArray *reps = self.multiPageImage.representations;
	if (!CHECK(arrayIndex < reps.count))
	{
		/*	I have seen this crash in Edinburgh, though I am not sure why.
			I imagine it might happen with a corrupted or half-written tiff file,
			although I'd expect the metadata to be written *after* the image.
			This logging should hopefully help pin down what dataset it occurs for
			(and protect against an outright crash).		*/
		NSLog(@"Check failed when reading %zd from %@", arrayIndex, self.imageFilename);
		return nil;
	}
	NSBitmapImageRep *result = (NSBitmapImageRep *)[reps objectAtIndex:arrayIndex];
	if (!CHECK([result isKindOfClass:[NSBitmapImageRep class]]))
		return nil;
	return result;
}

@synthesize frameMetadataArray = _frameMetadataArray;
@synthesize folderAlias = _folderAlias;
@synthesize imageFilename = _imageFilename;
@synthesize frameCount = _frameCount;
@synthesize deferMetadataSaving = _deferMetadataSaving;

@end
